/**
 * Post-build script: injects <link rel="modulepreload"> for the HomeModule
 * lazy chunk into the built index.html.
 *
 * Uses webpack stats.json (generated by --stats-json) to reliably find the
 * home-home-module chunk by name rather than guessing by file size or pattern.
 *
 * Intentionally NOT preloaded:
 *  - desktop-desktop-module — loaded only after "Enter Portfolio" click
 *  - game-game-module       — loaded only when the user opens the game
 *  - three-scene-impl       — loaded only when WebGL is confirmed available
 */
const fs = require('fs');
const path = require('path');

const distDir = path.join(__dirname, '../dist/portfolio-gianluca');
const indexPath = path.join(distDir, 'index.html');
const statsPath = path.join(distDir, 'stats.json');

if (!fs.existsSync(indexPath)) {
  console.warn('[inject-preload] index.html not found — skipping.');
  process.exit(0);
}

if (!fs.existsSync(statsPath)) {
  console.warn('[inject-preload] stats.json not found — run with --stats-json. Skipping.');
  process.exit(0);
}

const stats = JSON.parse(fs.readFileSync(statsPath, 'utf8'));

// Find the chunk named "home-home-module"
const homeChunk = stats.chunks && stats.chunks.find(c =>
  Array.isArray(c.names) && c.names.some(n => n === 'home-home-module')
);

if (!homeChunk || !homeChunk.files || homeChunk.files.length === 0) {
  console.warn('[inject-preload] home-home-module chunk not found in stats.json — skipping.');
  process.exit(0);
}

const homeChunkFile = homeChunk.files[0];
const preloadTag = `  <link rel="modulepreload" href="${homeChunkFile}">`;

let html = fs.readFileSync(indexPath, 'utf8');
if (html.includes(homeChunkFile)) {
  console.log(`[inject-preload] preload for ${homeChunkFile} already present — skipping.`);
  process.exit(0);
}

html = html.replace('</head>', `${preloadTag}\n</head>`);
fs.writeFileSync(indexPath, html);

const size = fs.existsSync(path.join(distDir, homeChunkFile))
  ? (fs.statSync(path.join(distDir, homeChunkFile)).size / 1024).toFixed(1) + ' KB'
  : '?';
console.log(`[inject-preload] Injected modulepreload for ${homeChunkFile} (${size})`);
