/**
 * Decodes a Radiance HDR file, box-filter downscales it, and writes back a
 * non-RLE Radiance HDR file (compatible with three.js's RGBELoader).
 *
 * Usage: node scripts/reduce-hdr.js <input.hdr> <output.hdr> <targetWidth>
 */
const parseHdr = require('parse-hdr');
const fs = require('fs');
const path = require('path');

const [, , inputArg, outputArg, targetWidthArg] = process.argv;
if (!inputArg || !outputArg || !targetWidthArg) {
  console.error('Usage: node scripts/reduce-hdr.js <input.hdr> <output.hdr> <targetWidth>');
  process.exit(1);
}

const inputPath = path.resolve(inputArg);
const outputPath = path.resolve(outputArg);
const targetWidth = parseInt(targetWidthArg, 10);

function frexp(value) {
  if (value === 0 || !Number.isFinite(value)) return [0, 0];
  const e = Math.floor(Math.log2(Math.abs(value))) + 1;
  const m = value / Math.pow(2, e);
  return [m, e];
}

/** Downscale RGBA float image with simple box filter (assumes integer ratio). */
function downscale(src, srcW, srcH, dstW, dstH) {
  const dst = new Float32Array(dstW * dstH * 4);
  const ratioX = srcW / dstW;
  const ratioY = srcH / dstH;

  for (let dy = 0; dy < dstH; dy++) {
    for (let dx = 0; dx < dstW; dx++) {
      let r = 0, g = 0, b = 0, count = 0;
      const sx0 = Math.floor(dx * ratioX);
      const sx1 = Math.floor((dx + 1) * ratioX);
      const sy0 = Math.floor(dy * ratioY);
      const sy1 = Math.floor((dy + 1) * ratioY);

      for (let sy = sy0; sy < sy1; sy++) {
        for (let sx = sx0; sx < sx1; sx++) {
          const idx = (sy * srcW + sx) * 4;
          r += src[idx];
          g += src[idx + 1];
          b += src[idx + 2];
          count++;
        }
      }
      const dIdx = (dy * dstW + dx) * 4;
      dst[dIdx] = r / count;
      dst[dIdx + 1] = g / count;
      dst[dIdx + 2] = b / count;
      dst[dIdx + 3] = 1.0;
    }
  }
  return dst;
}

/** Encode float RGBA image as Radiance HDR, non-RLE (raw RGBE per pixel). */
function encodeHdr(width, height, floatData) {
  const header = `#?RADIANCE\n# Generated by reduce-hdr.js\nFORMAT=32-bit_rle_rgbe\n\n-Y ${height} +X ${width}\n`;
  const headerBytes = Buffer.from(header, 'ascii');

  const numPixels = width * height;
  const pixels = Buffer.alloc(numPixels * 4);

  for (let i = 0; i < numPixels; i++) {
    const r = floatData[i * 4 + 0];
    const g = floatData[i * 4 + 1];
    const b = floatData[i * 4 + 2];
    const v = Math.max(r, g, b);

    if (v < 1e-32) {
      // pixels already 0 by default
      continue;
    }
    const [m, e] = frexp(v);
    const scale = (m * 256.0) / v;
    pixels[i * 4 + 0] = Math.min(255, Math.max(0, Math.floor(r * scale)));
    pixels[i * 4 + 1] = Math.min(255, Math.max(0, Math.floor(g * scale)));
    pixels[i * 4 + 2] = Math.min(255, Math.max(0, Math.floor(b * scale)));
    pixels[i * 4 + 3] = Math.min(255, Math.max(0, e + 128));
  }

  return Buffer.concat([headerBytes, pixels]);
}

(async () => {
  const inputBuf = fs.readFileSync(inputPath);
  const inputSize = inputBuf.length;

  const parsed = parseHdr(inputBuf);
  const [srcW, srcH] = parsed.shape;
  console.log(`[in]  ${path.basename(inputPath)} ${srcW}x${srcH} (${(inputSize / 1024).toFixed(1)} KB)`);

  // Preserve aspect ratio
  const targetHeight = Math.round((srcH / srcW) * targetWidth);

  if (srcW % targetWidth !== 0 || srcH % targetHeight !== 0) {
    console.warn(`[warn] non-integer downscale ratio (${srcW}/${targetWidth} = ${srcW / targetWidth}) — using floor sampling`);
  }

  const downscaled = downscale(parsed.data, srcW, srcH, targetWidth, targetHeight);
  const out = encodeHdr(targetWidth, targetHeight, downscaled);
  fs.writeFileSync(outputPath, out);

  const outSize = fs.statSync(outputPath).size;
  const reduction = ((1 - outSize / inputSize) * 100).toFixed(1);
  console.log(`[out] ${path.basename(outputPath)} ${targetWidth}x${targetHeight} (${(outSize / 1024).toFixed(1)} KB) -${reduction}%`);
})().catch((err) => {
  console.error(err);
  process.exit(1);
});
